version: '1'

services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    plan: free
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-julio.onrender.com     # ← Cambiar después del deploy
      - key: WEBHOOK_URL
        value: https://n8n-julio.onrender.com     # ← Cambiar después del deploy

      # Optimizaciones para Free tier (memoria)
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 168
      - key: N8N_DISABLE_PRODUCTION_MAIN_PROCESS
        value: true
      - key: EXECUTIONS_MODE
        value: queue
      - key: TZ
        value: America/La_Paz

    healthCheckPath: /
    autoDeploy: true
